version: 2

builds:
  - id: feed
    binary: feed
    main: ./cmd/feed
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/odysseus0/feed/internal/cli.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: feed
    repository:
      owner: odysseus0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/odysseus0/feed
    description: "RSS CLI for AI agents. Bring your own algorithm."
    license: MIT
    directory: Formula
